[[Libcroco]]
arch = "i686"
git-tree-sha1 = "ebb2adbe829c97e6f1a10da7c621b677c7bb3a72"
libc = "musl"
os = "linux"

    [[Libcroco.download]]
    sha256 = "847e2a340ae9b959583e21ea451d493eaeb0a24a567a938eaecbd93cf3f043da"
    url = "https://github.com/JuliaBinaryWrappers/Libcroco_jll.jl/releases/download/Libcroco-v0.6.13+1/Libcroco.v0.6.13.i686-linux-musl.tar.gz"
[[Libcroco]]
arch = "aarch64"
git-tree-sha1 = "9d251461302d3c77fd5db923eff79d553e7ce7b8"
libc = "musl"
os = "linux"

    [[Libcroco.download]]
    sha256 = "ee89439843cd9db48391343e3a0ee0f461b7e59bcfe4371e8d9d75ff449c8b68"
    url = "https://github.com/JuliaBinaryWrappers/Libcroco_jll.jl/releases/download/Libcroco-v0.6.13+1/Libcroco.v0.6.13.aarch64-linux-musl.tar.gz"
[[Libcroco]]
arch = "i686"
git-tree-sha1 = "d254ad808420913bbb87f15c32824ff0c64ee3ed"
os = "windows"

    [[Libcroco.download]]
    sha256 = "ad3fbf4b010fe018919a624c12c94d39067efaba8392bf0fd150e6517d68c857"
    url = "https://github.com/JuliaBinaryWrappers/Libcroco_jll.jl/releases/download/Libcroco-v0.6.13+1/Libcroco.v0.6.13.i686-w64-mingw32.tar.gz"
[[Libcroco]]
arch = "x86_64"
git-tree-sha1 = "2135336ef315329d80f3cc11177807891a7ed2a5"
os = "windows"

    [[Libcroco.download]]
    sha256 = "a868570cc1eaecedc33bb02fcb93c1f249c9a91a87a8e8335784a64097416c7d"
    url = "https://github.com/JuliaBinaryWrappers/Libcroco_jll.jl/releases/download/Libcroco-v0.6.13+1/Libcroco.v0.6.13.x86_64-w64-mingw32.tar.gz"
[[Libcroco]]
arch = "armv7l"
git-tree-sha1 = "ea6da702d81ab945b2a0552e4a69f0e3c1986f00"
libc = "glibc"
os = "linux"

    [[Libcroco.download]]
    sha256 = "6bfea85a9aad423570bd7834a4a7d809e6c45f0919f04fd96fe8eabfbdf9f791"
    url = "https://github.com/JuliaBinaryWrappers/Libcroco_jll.jl/releases/download/Libcroco-v0.6.13+1/Libcroco.v0.6.13.armv7l-linux-gnueabihf.tar.gz"
[[Libcroco]]
arch = "armv7l"
git-tree-sha1 = "3f1609cc2885529a4ee473ab6eea439bb4b3dcad"
libc = "musl"
os = "linux"

    [[Libcroco.download]]
    sha256 = "bddfaee70ac2c9f3aab27a0a936955f91e65277f50b90c937157a10e6bc02a28"
    url = "https://github.com/JuliaBinaryWrappers/Libcroco_jll.jl/releases/download/Libcroco-v0.6.13+1/Libcroco.v0.6.13.armv7l-linux-musleabihf.tar.gz"
[[Libcroco]]
arch = "i686"
git-tree-sha1 = "3f9b176eb0a4c0e87b17d8ab997a3ee36a02fc4f"
libc = "glibc"
os = "linux"

    [[Libcroco.download]]
    sha256 = "9d2afa736a86991ee5773f4a5ca247a60246902442e4e4a160de1ee3ab1967ba"
    url = "https://github.com/JuliaBinaryWrappers/Libcroco_jll.jl/releases/download/Libcroco-v0.6.13+1/Libcroco.v0.6.13.i686-linux-gnu.tar.gz"
[[Libcroco]]
arch = "x86_64"
git-tree-sha1 = "8d4271cc52f9cb70dcd888b76f75d6b6b50691cb"
libc = "glibc"
os = "linux"

    [[Libcroco.download]]
    sha256 = "45ffb99b95371f365c125e8dd00c814117569cf669afc3017059ffeb66f5a6e0"
    url = "https://github.com/JuliaBinaryWrappers/Libcroco_jll.jl/releases/download/Libcroco-v0.6.13+1/Libcroco.v0.6.13.x86_64-linux-gnu.tar.gz"
[[Libcroco]]
arch = "powerpc64le"
git-tree-sha1 = "4f683e589969443a7072a6a925b1a21f0d19179f"
libc = "glibc"
os = "linux"

    [[Libcroco.download]]
    sha256 = "0755d4a840791a6de93f1c7b409fcd2210e4ca8c2f980b240bfaccba3c1996cc"
    url = "https://github.com/JuliaBinaryWrappers/Libcroco_jll.jl/releases/download/Libcroco-v0.6.13+1/Libcroco.v0.6.13.powerpc64le-linux-gnu.tar.gz"
[[Libcroco]]
arch = "x86_64"
git-tree-sha1 = "894886992e492f84c33981d177805fb53e6593d0"
os = "macos"

    [[Libcroco.download]]
    sha256 = "523833a4a224dae60510a302295dd52fccf07843e646a1ee4376dce748269f1a"
    url = "https://github.com/JuliaBinaryWrappers/Libcroco_jll.jl/releases/download/Libcroco-v0.6.13+1/Libcroco.v0.6.13.x86_64-apple-darwin14.tar.gz"
[[Libcroco]]
arch = "aarch64"
git-tree-sha1 = "40b68e6e59d6cf29aebfb90e4779d9f0be2f0943"
libc = "glibc"
os = "linux"

    [[Libcroco.download]]
    sha256 = "ce2ce55872540bd9b14025ebff89a3cef439ad572e2fada87e3a7b4bedbe7558"
    url = "https://github.com/JuliaBinaryWrappers/Libcroco_jll.jl/releases/download/Libcroco-v0.6.13+1/Libcroco.v0.6.13.aarch64-linux-gnu.tar.gz"
[[Libcroco]]
arch = "x86_64"
git-tree-sha1 = "dc70940c297ec81deafc3e37a39cd52ea040b148"
os = "freebsd"

    [[Libcroco.download]]
    sha256 = "c97647a1073d9c2902a0a8f972e79a2d1154185c26f57205b7ca0c6cbb8205ae"
    url = "https://github.com/JuliaBinaryWrappers/Libcroco_jll.jl/releases/download/Libcroco-v0.6.13+1/Libcroco.v0.6.13.x86_64-unknown-freebsd11.1.tar.gz"
[[Libcroco]]
arch = "x86_64"
git-tree-sha1 = "2c7bc862762915fbcf6ee9ad73c8c0311889141d"
libc = "musl"
os = "linux"

    [[Libcroco.download]]
    sha256 = "63c8287370c969f182df8148ba241b4299c11a730d826ac8eb616713b5902b46"
    url = "https://github.com/JuliaBinaryWrappers/Libcroco_jll.jl/releases/download/Libcroco-v0.6.13+1/Libcroco.v0.6.13.x86_64-linux-musl.tar.gz"
