# Autogenerated wrapper script for Libcroco_jll for x86_64-unknown-freebsd
export libcroco

using Glib_jll
using XML2_jll
JLLWrappers.@generate_wrapper_header("Libcroco")
JLLWrappers.@declare_library_product(libcroco, "libcroco-0.6.so.3")
function __init__()
    JLLWrappers.@generate_init_header(Glib_jll, XML2_jll)
    JLLWrappers.@init_library_product(
        libcroco,
        "lib/libcroco-0.6.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
